// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package db

import (
	"context"
	"time"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at
`

type CreateCollectionParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	Color       *string `json:"color"`
	ParentID    *int64  `json:"parent_id"`
	SortOrder   *int64  `json:"sort_order"`
	IsPublic    *int64  `json:"is_public"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Color,
		arg.ParentID,
		arg.SortOrder,
		arg.IsPublic,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
		&i.ParentID,
		&i.SortOrder,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getBookmarksByCollectionID = `-- name: GetBookmarksByCollectionID :many
SELECT id, title, url, domain, is_public, is_favorite, created_at
FROM bookmarks
WHERE collection_id = ?
ORDER BY COALESCE(sort_order, 999999) ASC, updated_at DESC
LIMIT 6
`

type GetBookmarksByCollectionIDRow struct {
	ID         int64      `json:"id"`
	Title      string     `json:"title"`
	Url        string     `json:"url"`
	Domain     *string    `json:"domain"`
	IsPublic   *int64     `json:"is_public"`
	IsFavorite *int64     `json:"is_favorite"`
	CreatedAt  *time.Time `json:"created_at"`
}

func (q *Queries) GetBookmarksByCollectionID(ctx context.Context, collectionID *int64) ([]GetBookmarksByCollectionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksByCollectionID, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookmarksByCollectionIDRow{}
	for rows.Next() {
		var i GetBookmarksByCollectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Domain,
			&i.IsPublic,
			&i.IsFavorite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionBookmarkCount = `-- name: GetCollectionBookmarkCount :one
SELECT COUNT(*) FROM bookmarks WHERE collection_id = ?
`

func (q *Queries) GetCollectionBookmarkCount(ctx context.Context, collectionID *int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCollectionBookmarkCount, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at FROM collections WHERE id = ?
`

func (q *Queries) GetCollectionByID(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
		&i.ParentID,
		&i.SortOrder,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at FROM collections WHERE slug = ?
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Color,
		&i.ParentID,
		&i.SortOrder,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentBookmarksByCollectionID = `-- name: GetRecentBookmarksByCollectionID :many
SELECT id, title, url, domain, is_favorite, is_public, updated_at
FROM bookmarks
WHERE collection_id = ?
ORDER BY COALESCE(sort_order, 999999) ASC, updated_at DESC
LIMIT ?
`

type GetRecentBookmarksByCollectionIDParams struct {
	CollectionID *int64 `json:"collection_id"`
	Limit        int64  `json:"limit"`
}

type GetRecentBookmarksByCollectionIDRow struct {
	ID         int64      `json:"id"`
	Title      string     `json:"title"`
	Url        string     `json:"url"`
	Domain     *string    `json:"domain"`
	IsFavorite *int64     `json:"is_favorite"`
	IsPublic   *int64     `json:"is_public"`
	UpdatedAt  *time.Time `json:"updated_at"`
}

func (q *Queries) GetRecentBookmarksByCollectionID(ctx context.Context, arg GetRecentBookmarksByCollectionIDParams) ([]GetRecentBookmarksByCollectionIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentBookmarksByCollectionID, arg.CollectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentBookmarksByCollectionIDRow{}
	for rows.Next() {
		var i GetRecentBookmarksByCollectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Domain,
			&i.IsFavorite,
			&i.IsPublic,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollections = `-- name: ListAllCollections :many
SELECT id, name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at FROM collections ORDER BY sort_order, name
`

func (q *Queries) ListAllCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listAllCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
			&i.ParentID,
			&i.SortOrder,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollectionsWithCounts = `-- name: ListAllCollectionsWithCounts :many
SELECT c.id, c.name, c.slug, c.description, c.color, c.parent_id, c.sort_order, c.is_public, c.created_at, c.updated_at, 
    (SELECT COUNT(*) FROM bookmarks b WHERE b.collection_id = c.id) as bookmark_count
FROM collections c
ORDER BY c.sort_order, c.name
`

type ListAllCollectionsWithCountsRow struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Slug          string     `json:"slug"`
	Description   *string    `json:"description"`
	Color         *string    `json:"color"`
	ParentID      *int64     `json:"parent_id"`
	SortOrder     *int64     `json:"sort_order"`
	IsPublic      *int64     `json:"is_public"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
	BookmarkCount int64      `json:"bookmark_count"`
}

func (q *Queries) ListAllCollectionsWithCounts(ctx context.Context) ([]ListAllCollectionsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCollectionsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCollectionsWithCountsRow{}
	for rows.Next() {
		var i ListAllCollectionsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
			&i.ParentID,
			&i.SortOrder,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookmarkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCollections = `-- name: ListPublicCollections :many
SELECT id, name, slug, description, color, parent_id, sort_order, is_public, created_at, updated_at FROM collections WHERE is_public = 1 ORDER BY sort_order, name
`

func (q *Queries) ListPublicCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listPublicCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
			&i.ParentID,
			&i.SortOrder,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCollectionsWithCounts = `-- name: ListPublicCollectionsWithCounts :many
SELECT c.id, c.name, c.slug, c.description, c.color, c.parent_id, c.sort_order, c.is_public, c.created_at, c.updated_at, 
    (SELECT COUNT(*) FROM bookmarks b WHERE b.collection_id = c.id) as bookmark_count
FROM collections c
WHERE c.is_public = 1
ORDER BY c.sort_order, c.name
`

type ListPublicCollectionsWithCountsRow struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Slug          string     `json:"slug"`
	Description   *string    `json:"description"`
	Color         *string    `json:"color"`
	ParentID      *int64     `json:"parent_id"`
	SortOrder     *int64     `json:"sort_order"`
	IsPublic      *int64     `json:"is_public"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
	BookmarkCount int64      `json:"bookmark_count"`
}

func (q *Queries) ListPublicCollectionsWithCounts(ctx context.Context) ([]ListPublicCollectionsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicCollectionsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicCollectionsWithCountsRow{}
	for rows.Next() {
		var i ListPublicCollectionsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Color,
			&i.ParentID,
			&i.SortOrder,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BookmarkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections 
SET name = ?, slug = ?, description = ?, color = ?,
    parent_id = ?, sort_order = ?, is_public = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

type UpdateCollectionParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	Color       *string `json:"color"`
	ParentID    *int64  `json:"parent_id"`
	SortOrder   *int64  `json:"sort_order"`
	IsPublic    *int64  `json:"is_public"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Color,
		arg.ParentID,
		arg.SortOrder,
		arg.IsPublic,
		arg.ID,
	)
	return err
}

const updateCollectionName = `-- name: UpdateCollectionName :exec

UPDATE collections SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

// ============================================
// INLINE EDITING QUERIES
// ============================================
func (q *Queries) UpdateCollectionName(ctx context.Context, arg UpdateCollectionNameParams) error {
	_, err := q.db.ExecContext(ctx, updateCollectionName, arg.Name, arg.ID)
	return err
}

const updateCollectionPublic = `-- name: UpdateCollectionPublic :exec
UPDATE collections SET is_public = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionPublicParams struct {
	IsPublic *int64 `json:"is_public"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCollectionPublic(ctx context.Context, arg UpdateCollectionPublicParams) error {
	_, err := q.db.ExecContext(ctx, updateCollectionPublic, arg.IsPublic, arg.ID)
	return err
}
