// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
`

func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (hash, content_type, data, size, source_url)
VALUES (?, ?, ?, ?, ?)
RETURNING id, hash, content_type, data, size, source_url, created_at
`

type CreateImageParams struct {
	Hash        string  `json:"hash"`
	ContentType string  `json:"content_type"`
	Data        []byte  `json:"data"`
	Size        int64   `json:"size"`
	SourceUrl   *string `json:"source_url"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.Hash,
		arg.ContentType,
		arg.Data,
		arg.Size,
		arg.SourceUrl,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ContentType,
		&i.Data,
		&i.Size,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteUnusedImages = `-- name: DeleteUnusedImages :exec
DELETE FROM images 
WHERE id NOT IN (
    SELECT cover_image_id FROM bookmarks WHERE cover_image_id IS NOT NULL
    UNION
    SELECT favicon_id FROM bookmarks WHERE favicon_id IS NOT NULL
)
`

func (q *Queries) DeleteUnusedImages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedImages)
	return err
}

const getImageByHash = `-- name: GetImageByHash :one
SELECT id, hash, content_type, data, size, source_url, created_at FROM images WHERE hash = ?
`

func (q *Queries) GetImageByHash(ctx context.Context, hash string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByHash, hash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ContentType,
		&i.Data,
		&i.Size,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, hash, content_type, data, size, source_url, created_at FROM images WHERE id = ?
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ContentType,
		&i.Data,
		&i.Size,
		&i.SourceUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getImageStats = `-- name: GetImageStats :one
SELECT 
    COUNT(*) as count,
    COALESCE(SUM(size), 0) as total_size
FROM images
`

type GetImageStatsRow struct {
	Count     int64       `json:"count"`
	TotalSize interface{} `json:"total_size"`
}

func (q *Queries) GetImageStats(ctx context.Context) (GetImageStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getImageStats)
	var i GetImageStatsRow
	err := row.Scan(&i.Count, &i.TotalSize)
	return i, err
}
