// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Activity struct {
	ID          int64      `json:"id"`
	Action      string     `json:"action"`
	EntityType  string     `json:"entity_type"`
	EntityID    *int64     `json:"entity_id"`
	EntityTitle *string    `json:"entity_title"`
	Metadata    *string    `json:"metadata"`
	CreatedAt   *time.Time `json:"created_at"`
}

type Bookmark struct {
	ID           int64      `json:"id"`
	Url          string     `json:"url"`
	Title        string     `json:"title"`
	Description  *string    `json:"description"`
	Excerpt      *string    `json:"excerpt"`
	CoverImage   *string    `json:"cover_image"`
	Favicon      *string    `json:"favicon"`
	Domain       *string    `json:"domain"`
	CollectionID *int64     `json:"collection_id"`
	IsPublic     *int64     `json:"is_public"`
	IsFavorite   *int64     `json:"is_favorite"`
	SortOrder    *int64     `json:"sort_order"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type BookmarkTag struct {
	BookmarkID int64      `json:"bookmark_id"`
	TagID      int64      `json:"tag_id"`
	CreatedAt  *time.Time `json:"created_at"`
}

type Collection struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Description *string    `json:"description"`
	Color       *string    `json:"color"`
	ParentID    *int64     `json:"parent_id"`
	SortOrder   *int64     `json:"sort_order"`
	IsPublic    *int64     `json:"is_public"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type Post struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Content     string     `json:"content"`
	Excerpt     *string    `json:"excerpt"`
	CoverImage  *string    `json:"cover_image"`
	IsDraft     *int64     `json:"is_draft"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type PostTag struct {
	PostID    int64      `json:"post_id"`
	TagID     int64      `json:"tag_id"`
	CreatedAt *time.Time `json:"created_at"`
}

type Session struct {
	ID        string     `json:"id"`
	UserID    int64      `json:"user_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt *time.Time `json:"created_at"`
}

type Tag struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	Color     *string    `json:"color"`
	CreatedAt *time.Time `json:"created_at"`
}

type User struct {
	ID           int64      `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}
