// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
	"time"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO post_tags (post_id, tag_id, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)
`

type AddPostTagParams struct {
	PostID int64 `json:"post_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.ExecContext(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const countAllPosts = `-- name: CountAllPosts :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) CountAllPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedPosts = `-- name: CountPublishedPosts :one
SELECT COUNT(*) FROM posts WHERE is_draft = 0
`

func (q *Queries) CountPublishedPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Content     string     `json:"content"`
	Excerpt     *string    `json:"excerpt"`
	CoverImage  *string    `json:"cover_image"`
	IsDraft     *int64     `json:"is_draft"`
	PublishedAt *time.Time `json:"published_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.CoverImage,
		arg.IsDraft,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImage,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const deletePostTags = `-- name: DeletePostTags :exec
DELETE FROM post_tags WHERE post_id = ?
`

func (q *Queries) DeletePostTags(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, deletePostTags, postID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at FROM posts WHERE id = ?
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImage,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT id, title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at FROM posts WHERE slug = ?
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImage,
		&i.IsDraft,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostTags = `-- name: GetPostTags :many
SELECT t.id, t.name, t.slug, t.color, t.created_at
FROM tags t
INNER JOIN post_tags pt ON t.id = pt.tag_id
WHERE pt.post_id = ?
`

func (q *Queries) GetPostTags(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getPostTags, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at FROM posts 
ORDER BY COALESCE(published_at, created_at) DESC 
LIMIT ? OFFSET ?
`

type ListAllPostsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listAllPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.CoverImage,
			&i.IsDraft,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, content, excerpt, cover_image, is_draft, published_at, created_at, updated_at FROM posts 
WHERE is_draft = 0 
ORDER BY COALESCE(published_at, created_at) DESC 
LIMIT ? OFFSET ?
`

type ListPublishedPostsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.CoverImage,
			&i.IsDraft,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts 
SET title = ?, slug = ?, content = ?, excerpt = ?, cover_image = ?, 
    is_draft = ?, published_at = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = ?
`

type UpdatePostParams struct {
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Content     string     `json:"content"`
	Excerpt     *string    `json:"excerpt"`
	CoverImage  *string    `json:"cover_image"`
	IsDraft     *int64     `json:"is_draft"`
	PublishedAt *time.Time `json:"published_at"`
	ID          int64      `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.CoverImage,
		arg.IsDraft,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
