// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"time"
)

const countDraftPosts = `-- name: CountDraftPosts :one
SELECT COUNT(*) FROM posts WHERE is_draft = 1
`

func (q *Queries) CountDraftPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDraftPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookmarkCountsByCollection = `-- name: GetBookmarkCountsByCollection :many
SELECT 
    COALESCE(c.name, 'Unsorted') as collection_name,
    COALESCE(c.color, '') as collection_color,
    COUNT(b.id) as bookmark_count
FROM bookmarks b
LEFT JOIN collections c ON b.collection_id = c.id
GROUP BY b.collection_id
ORDER BY bookmark_count DESC
LIMIT ?
`

type GetBookmarkCountsByCollectionRow struct {
	CollectionName  string `json:"collection_name"`
	CollectionColor string `json:"collection_color"`
	BookmarkCount   int64  `json:"bookmark_count"`
}

func (q *Queries) GetBookmarkCountsByCollection(ctx context.Context, limit int64) ([]GetBookmarkCountsByCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarkCountsByCollection, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookmarkCountsByCollectionRow{}
	for rows.Next() {
		var i GetBookmarkCountsByCollectionRow
		if err := rows.Scan(&i.CollectionName, &i.CollectionColor, &i.BookmarkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksCreatedSince = `-- name: GetBookmarksCreatedSince :one
SELECT COUNT(*) FROM bookmarks
WHERE created_at >= ?
`

func (q *Queries) GetBookmarksCreatedSince(ctx context.Context, createdAt *time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBookmarksCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDatabaseStats = `-- name: GetDatabaseStats :one
SELECT 
    (SELECT COUNT(*) FROM bookmarks) as total_bookmarks,
    (SELECT COUNT(*) FROM posts) as total_posts,
    (SELECT COUNT(*) FROM collections) as total_collections,
    (SELECT COUNT(*) FROM tags) as total_tags
`

type GetDatabaseStatsRow struct {
	TotalBookmarks   int64 `json:"total_bookmarks"`
	TotalPosts       int64 `json:"total_posts"`
	TotalCollections int64 `json:"total_collections"`
	TotalTags        int64 `json:"total_tags"`
}

func (q *Queries) GetDatabaseStats(ctx context.Context) (GetDatabaseStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseStats)
	var i GetDatabaseStatsRow
	err := row.Scan(
		&i.TotalBookmarks,
		&i.TotalPosts,
		&i.TotalCollections,
		&i.TotalTags,
	)
	return i, err
}

const getPostsCreatedSince = `-- name: GetPostsCreatedSince :one
SELECT COUNT(*) FROM posts
WHERE created_at >= ?
`

func (q *Queries) GetPostsCreatedSince(ctx context.Context, createdAt *time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostsCreatedSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTopDomains = `-- name: GetTopDomains :many
SELECT 
    domain,
    COUNT(*) as count
FROM bookmarks
WHERE domain IS NOT NULL AND domain != ''
GROUP BY domain
ORDER BY count DESC
LIMIT ?
`

type GetTopDomainsRow struct {
	Domain *string `json:"domain"`
	Count  int64   `json:"count"`
}

func (q *Queries) GetTopDomains(ctx context.Context, limit int64) ([]GetTopDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopDomains, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopDomainsRow{}
	for rows.Next() {
		var i GetTopDomainsRow
		if err := rows.Scan(&i.Domain, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
