// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, created_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
RETURNING id, name, slug, created_at
`

type CreateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getPostsByTagID = `-- name: GetPostsByTagID :many
SELECT p.id, p.title, p.slug, p.is_draft, p.published_at, p.created_at
FROM posts p
JOIN post_tags pt ON p.id = pt.post_id
WHERE pt.tag_id = ?
ORDER BY p.created_at DESC
`

type GetPostsByTagIDRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	IsDraft     *int64     `json:"is_draft"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   *time.Time `json:"created_at"`
}

func (q *Queries) GetPostsByTagID(ctx context.Context, tagID int64) ([]GetPostsByTagIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByTagID, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByTagIDRow{}
	for rows.Next() {
		var i GetPostsByTagIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.IsDraft,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, slug, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, created_at FROM tags WHERE slug = ?
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, created_at FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCounts = `-- name: ListTagsWithCounts :many
SELECT t.id, t.name, t.slug, t.created_at,
    (SELECT COUNT(*) FROM post_tags pt WHERE pt.tag_id = t.id) as usage_count
FROM tags t
ORDER BY usage_count DESC, t.name
`

type ListTagsWithCountsRow struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	Slug       string     `json:"slug"`
	CreatedAt  *time.Time `json:"created_at"`
	UsageCount int64      `json:"usage_count"`
}

func (q *Queries) ListTagsWithCounts(ctx context.Context) ([]ListTagsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithCountsRow{}
	for rows.Next() {
		var i ListTagsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
